### ISSUE TITLE
[SOLVED] No upload after flickr validation

### ISSUE THREAD

**Issue by usky73** [syno2flickr/syno2flickr#3]
Bonjour,

I face a problem when launching java application.
the program is running, asking to "Please enter the following URL into a browser, follow the instructions, and then come back".

I did, validate the access to this application, and then nothing happens ...

Can you please help me ?

**Comment by syno2flickr** [comment]
@usky73 
Hi,
what is your OS (Windows XP/7/8, Mac OS X, Linux?), your java version and your syno2flickr version (0.1, 0.1.1 or 0.1.2)?
Do you have any error message (from Flickr or syno2flickr)? I cannot help you without more information. I need to reproduce the problem.

**Comment by usky73** [comment]
Hi,

I am under ubuntu (Linux) running throught a terminal.
The NAS is a 212j under DSM 4.2
You syno2flickr java program is the 0.1.2

The message I got when launching the program : 

DS-212j> java -jar syno2flickr-0.1.2.jar syno2flickr.properties 

---
- Syno2Flickr v0.1.2 07/2013                                         *
-                                                                    *
  **********************************************************************
  Properties file 'syno2flickr.properties' loaded successfully.
  Aug 11, 2013 3:39:12 PM java.util.prefs.FileSystemPreferences$2 run
  INFO: Created user preferences directory.
  Please enter the following URL into a browser, follow the instructions, and then come back
  http://www.flickr.com/services/auth/?api_key=05a96105a67932777a50a5d869d62df4&frob=721576350.........

I copy the link, validate the access on flickr, and then nothing happen...

Thank you for your help !

**Comment by syno2flickr** [comment]
@usky73
Ok thank you for informations.
Can you go to the url https://secure.flickr.com/account/sharing/ and make sure "Syno2Flickr" is in the list of "Accounts links"?
After going on the URL given by the program, when you came back to the terminal did you press ENTER?

**Comment by usky73** [comment]
Great !
I thought the downloading will start automaticaly.
I only had to press enter !

Thank you for this program and for the support.

**Comment by syno2flickr** [comment]
Good. I will change the message in next version. It was not very intuitive.
