### ISSUE TITLE
-ash: java: not found

### ISSUE THREAD

**Issue by freeman59** [syno2flickr/syno2flickr#4]
Hi

Just have a problem since DSM update. I used the 0.1.2 version and 0.2.0 too

System said  -ash: java: not found

So I've uninstalled Java SE 6 and reinstalled it : same problem. Tryied with Java SE 7, not working too

Any idea ?

Ok if you have the same pb, just kill your SSH connexion and retry : it's work !

**Comment by syno2flickr** [comment]
Problem was : the path of java wasn't in your PATH environment variable. Maybe because you did a su and you lost your profile environment. 

I close this issue.
