### ISSUE TITLE
Flickr does only accept HTTPS for authorisation

### ISSUE THREAD

**Issue by AJOCHAM** [syno2flickr/syno2flickr#5]
Flickr does only accept HTTPS for authorisation
I cannot find the right spot to change the url

Thanks for your help
Andy

**Comment by syno2flickr** [comment]
Hi @AJOCHAM, new version v0.2.1 with HTTPS support is released. Thank you for your support.

**Comment by AJOCHAM** [comment]
works just fine, thanks
